### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#12]
**Is your feature request related to a problem? Please describe.**
The current documentation is created from `typedoc` which isn't that great for something like this.

**Describe the solution you'd like**
Better hand written documentation.

**Describe alternatives you've considered**
Creating a documentation framework with `lucia`.

**Comment by aidenybai** [comment]
+1 this, any suggestions for what we should use?

**Comment by shadowtime2000** [comment]
We could use [Docusaurus](https://docusaurus.io/) or we could create our own documentation framework with `lucia` but I think we should move the documentation out of the `README`.

**Comment by aidenybai** [comment]
Agreed

**Comment by shadowtime2000** [comment]
I think creating our own documentation framework with `lucia` may be somewhat hard but I would be willing to try it out.

@aidenybai Thoughts?

**Comment by aidenybai** [comment]
@shadowtime2000 

Sure! Go ahead if you are interested

**Comment by aidenybai** [comment]
A possible solution for this could be either different repo for this or we could do a mono repo or have a `docs` branch. Let me know which one works best for you

**Comment by shadowtime2000** [comment]
I think it would be best to keep them separate. Once I get a working version I will create a repo.

**Comment by shadowtime2000** [comment]
Trying it out, it is pretty difficult. I think we should then use a static site generator (don't know any for documentation) or Docusaurus.

**Comment by aidenybai** [comment]
Got it. We could take a look at [Vuepress](https://vuepress.vuejs.org/) as an alternative as well. Seems like it supports markdown

**Comment by octetd** [comment]
[Hugo](https://gohugo.io/) has some docs templates if you feel like looking into it

**Comment by aidenybai** [comment]
Just took a look at Docusaurus - seems great for our use case. It's a bit awkward to transfer to an org at this stage as it would break a lot of backlinks, do you think it would be possible to do it in another branch? Current docs deploy via Netlify so it's perfect for us.

**Comment by shadowtime2000** [comment]
> Just took a look at Docusaurus - seems great for our use case. It's a bit awkward to transfer to an org at this stage as it would break a lot of backlinks, do you think it would be possible to do it in another branch? Current docs deploy via Netlify so it's perfect for us. It sounds a bit janky though, another possible solution could be making a new repo.

I don't have much experience with React so you guys might be to be more help on this 😆

@aidenybai I think transferring to an org may be the best solution. From my experience keeping the docs in another branch is a **little** messy. A new repo could also be a good solution, or we could just make this a monorepo and use something like `pnpm`. If we transfer to an org we could do what [gotwarlost](https://github.com/gotwarlost) did with the `instanbul` test coverage tool and write a deprecation notice on this pointing people to the org.

**Comment by aidenybai** [comment]
I'm a little hesitant of transferring to an org just for a few reasons as Lucia doubles as my school research project, and it's a bit awkward for me to transfer this specific repo. I don't think they'll care about the external repos, so what I'm going to do is first create an org for Lucia for docs, etc and once the project period is over (Feb-Mar) I will transfer this repo over.

**Comment by shadowtime2000** [comment]
That sounds good to me.

**Comment by shadowtime2000** [comment]
@aidenybai Should I initialize a Docusaurus site on the docs repo and start working on it?

**Comment by aidenybai** [comment]
@shadowtime2000 Yeah, that would be great. Let me know when it's in a stable condition and I can add the lucia.js.org domain

**Comment by shadowtime2000** [comment]
Because of how the docusaurus template work I will need to delete the repo and then create another one.

**Comment by aidenybai** [comment]
That's fine, go ahead

**Comment by shadowtime2000** [comment]
The Docusaurus site is in [this repo](https://github.com/lucialand/lucia-docs). I think you can connect it to your hosting provider. It does require that `npm run build` is run before it is hosted but I think it is good to go.

**Comment by aidenybai** [comment]
Is there a dist directory for the bundled files?

**Comment by shadowtime2000** [comment]
@aidenybai `build` is the dist directory.

**Comment by aidenybai** [comment]
![image](https://user-images.githubusercontent.com/38025074/97487546-4147ca00-191a-11eb-8599-c94529f3d77c.png)
Recieving these errors on deploy

**Comment by shadowtime2000** [comment]
@aidenybai Fixed!

**Comment by aidenybai** [comment]
Should be published! https://lucia.js.org/

I see that you have a blog as well - do you want to lead maintaining the docs + blog?

**Comment by shadowtime2000** [comment]
> I see that you have a blog as well - do you want to lead maintaining the docs + blog?

@aidenybai Sure!

**Comment by shadowtime2000** [comment]
Just a question, @aidenybai what do you use to host the website?

**Comment by aidenybai** [comment]
Netlify

**Comment by aidenybai** [comment]
Kind of a aesthetic thing - would it be possible to change the theme colors to Lucia colors?

**Comment by shadowtime2000** [comment]
Yeah, the preset I used uses the [Infima](https://facebookincubator.github.io/infima/) CSS framework which allows you to change the theme colors with CSS custom variables I believe.
