### ISSUE TITLE
Change Copyright in License to something Lucia related?

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/lucia#13]
https://github.com/aidenybai/lucia/blob/12a26b65a5544098b6ed4770e4de35d65de6f5c3/LICENSE#L3

**Comment by shadowtime2000** [comment]
For one of my projects [SwordCSS](https://github.com/swordcss/swordcss) I changed all the copyrights from my name to "The swordcss Team" so we could probably do something like that.

**Comment by aidenybai** [comment]
Implemeted in afa493560c9d37de3f9f8397c0af69e8273a2c27
