### ISSUE TITLE
Coverage Reporting

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#14]
**Is your feature request related to a problem? Please describe.**

You currently have to clone the project to look at test coverage.

**Describe the solution you'd like**

Test coverage reporting with coveralls.

**Describe alternatives you've considered**

Using other coverage reporting tools.

**Additional context**
I can do this, it is pretty simple, just looking to see the thoughts of others.

**Comment by aidenybai** [comment]
Sounds fine by me. :+1:
