### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#15]
**Is your feature request related to a problem? Please describe.**
People see from the docs and the README that Lucia is fast but they don't have much proof.

**Describe the solution you'd like**
Lucia benchmarks added to [the JS Framework Benchmark](https://github.com/krausest/js-framework-benchmark).

**Describe alternatives you've considered**
None.

**Comment by aidenybai** [comment]
Agreed. Let's try to do this after we finish maestro

**Comment by shadowtime2000** [comment]
Seems like a good idea since Maestro will hopefully give it a performance boost anyways.

**Comment by aidenybai** [comment]
Any plans to start on this for 0.3.0?

**Comment by shadowtime2000** [comment]
I think I will start attempting it since progress on Maestro has been pretty slow.

**Comment by aidenybai** [comment]
Unsure how to work on this - should we follow an official benchmarking or our own

**Comment by shadowtime2000** [comment]
We could probably write our own for the basic simple stuff at a medium scale and write for a more community standard benchmark if we feel it is necessary.

**Comment by aidenybai** [comment]
This is a good idea - do you have any suggestions on how to benchmark? Here's some I've found:
- `performance.now()`
- `new Date() - new Date()`

Unsure if there are any good libraries for our use case

**Comment by shadowtime2000** [comment]
@aidenybai [benchmark.js](https://benchmarkjs.com/) is one I have used in a couple scenarios and is pretty detailed - or at least for my use case which was only speed

**Comment by aidenybai** [comment]
@shadowtime2000 Looks really promising
