### ISSUE TITLE
Create One Function For Computing

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#16]
**Is your feature request related to a problem? Please describe.**
Currently when evaluating expressions it creates a function binds the `$view` to `this` uses `with (this)` and then calls the function.

**Describe the solution you'd like**
At startup for it read all `l-` directives and create functions with the expressions, and bind and call when it is necessary. This would also mean that changing `l-` directives wouldn't change anything which is kind of a bonus. This should make it a little more performant and possibly more secure.

**Describe alternatives you've considered**
None.

**Additional context**
This would require a restructure in the codebase so we should probably wait for Maestro to be completed (#8)

**Comment by aidenybai** [comment]
Done in 4c65cd510f61352472d87cc217800c0abc481f4e
