### ISSUE TITLE
Stop Using With

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#19]
**Is your feature request related to a problem? Please describe.**
`with` is deprecated as it isn't that good for performance.

**Describe the solution you'd like**
Removing the `with` statements inside `compute`. This will make it so that users must use `this.whatever` instead of `whatever`.

**Describe alternatives you've considered**
None

**Additional context**
This is pretty simple but since it is a breaking change we should probably pile with the other ones in the `vdom-refactor` branch.

**Comment by shadowtime2000** [comment]
@aidenybai @octetd Thoughts?

**Comment by aidenybai** [comment]
Fine by me, keeps a bit of consistency

**Comment by aidenybai** [comment]
Also, a bit offtopic but you should join the Discord, this way we can have conversations off of Github issues and keep the issues tracker for more specific things
