### ISSUE TITLE
State Management Library

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#20]
**Is your feature request related to a problem? Please describe.**
There is no way to do a little more complex state management.

**Describe the solution you'd like**
A state management library.

**Describe alternatives you've considered**
None.

**Additional context**
I can spearhead this. Ideas for names would be great, I am thinking of Luciex.

**Comment by aidenybai** [comment]
Sounds good. I imagine this would depend on the vdom-refactor?

**Comment by shadowtime2000** [comment]
@aidenybai Not necessarily. We could structure it in a way where we have a core `@luciex/core` package with `@luciex/lucia` binding package. That way it can be used for other things. If we restructure the project right with `vdom-refactor` we probably wouldn't have to change anything between this being released and Maestro being completed.

**Comment by shadowtime2000** [comment]
We should also put it inside it's own repo in the @lucialand org

**Comment by aidenybai** [comment]
Agreed

**Comment by shadowtime2000** [comment]
Ok, I will start working on it. I am thinking we do a dispatch design where you do something like this:

```typescript
import { Store } from "@luciex/core";

const num = new Store(0);

const increment = n => n + 1;

num.dispatch(increment);
```

**Comment by shadowtime2000** [comment]
@aidenybai I kind of finished it but for some reason I am getting errors when publishing.

**Comment by aidenybai** [comment]
What's the error with it?

**Comment by shadowtime2000** [comment]
@aidenybai Seems to be something with error 404 when sending PUT to the registry. I am trying to fix it right now.

**Comment by shadowtime2000** [comment]
It looks like it a problem with how `lerna` is publishing it.

**Comment by shadowtime2000** [comment]
According to [this comment](https://github.com/lerna/lerna/issues/1821#issuecomment-448473941) the first publish should be by hand, so I am going to do it that way.

**Comment by shadowtime2000** [comment]
Figured it out, using a scope for a package requires an NPM organization, and right now, it isn't very necessary, so I am going to do away with the scope ideas and have it be published under the name `luciex`.

**Comment by shadowtime2000** [comment]
🎉 [luciex](https://www.npmjs.com/package/luciex) has been published. We probably need to do some cleaning up with the READMEs and stuff. We could also try getting `luciex.js.org` and putting some docs there.
