### ISSUE TITLE
Bundle Typings

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#21]
**Is your feature request related to a problem? Please describe.**
Once Maestro is completed and that version is released, a feature request was to have an exported `init` function.

**Describe the solution you'd like**
It would probably be a good idea to start bundling Typescript declaration files instead of using `babel-preset-typescript`.

**Describe alternatives you've considered**
None.

**Additional context**
This is so simple we could just do it on the `master` branch and then release it as `v0.2.0`.

**Comment by shadowtime2000** [comment]
@aidenybai @octetd Thoughts?

**Comment by aidenybai** [comment]
Sounds good to me. Can we merge the new `this` changes in directive values and minor changes

**Comment by shadowtime2000** [comment]
@aidenybai I think the `this` change would be considered a breaking change because it is not backwards compatible.

**Comment by aidenybai** [comment]
Got it, sounds good then

**Comment by aidenybai** [comment]
Pushed a change 05089752e539841cab7d3c1d00e6dc5f651d6036 for this

**Comment by shadowtime2000** [comment]
@aidenybai imo we should use a typescript plugin for rollup to create the typings instead.

**Comment by aidenybai** [comment]
> @aidenybai imo we should use a typescript plugin for rollup to create the typings instead.

I looked at some typescript plugins for rollup and they don't seem to support typings and actually recommend using `tsc`. Do you have any plugins in mind we could use?

**Comment by shadowtime2000** [comment]
@aidenybai I was thinking using [rollup-plugin-typescript2](https://www.npmjs.com/package/rollup-plugin-typescript2). Since it allows us to pass in certain configuration, we could pass `declaration: true` and attempt to turn everything else off. I was thinking that we should move away from using `babel-preset-typescript` too to make it a little simpler.

**Comment by aidenybai** [comment]
Should be done 👍

**Comment by shadowtime2000** [comment]
@aidenybai Yeah, I saw that you released `v0.2.0`, but I don't believe the `types` field was in the `package.json` at that moment, so once we create a new release we can close this.

**Comment by shadowtime2000** [comment]
I believe the `v0.2.1` release fixed this so I am going to close this.
