### ISSUE TITLE
SSG/SSR

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#22]
**Is your feature request related to a problem? Please describe.**
There should be a way to create pure static HTML from Lucia components.

**Describe the solution you'd like**
A package (`lucia-render`?) that exports functions like `renderToMarkup` and `renderToStaticMarkup` to create reactive and static apps appropriately which are prerendered.

**Describe alternatives you've considered**
Server side rendering but really that could simply be based on the functions described above.

**Additional context**
We should probably take a go at this once #7 is done so you can just call `renderToStaticMarkup` on a component.

**Comment by shadowtime2000** [comment]
It should be relatively simple to generate purely static markup from a component though generating reactive markup may be a little harder. I don't have much of an idea on how I would get hydration and stuff to work with the current system.

**Comment by aidenybai** [comment]
I added a simple `render` function under `h.ts` and is exported under `Lucia`. Hydration I feel currently isn't necessary as we're relying on directives, but we can look into that.

**Comment by shadowtime2000** [comment]
That works on the client side, we should probably do something like `lucia-ssr` which does it on the server side. It should allow passing in `h` calls for the app I guess.

**Comment by aidenybai** [comment]
Closed for inactivity
