### ISSUE TITLE
Allow Usage of Template Engines

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#23]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to use templating syntax to make interpolation of values easier.

**Describe the solution you'd like**
A `l-templating:precompile` directive directive for their appropriate uses. On initialization it should take the full inner HTML of elements using the `l-tempating:precompile` directive and use the value of that directive to precompile the inner HTML into a function. Then, on data changes it calls that function and resets the inner HTML accordingly.

**Describe alternatives you've considered**
Rendering on the fly with a directive like `l-templating:render` but that is less efficient and could be added later.

**Additional context**
#8 will probably cause structural changes so this could tag along with that.

**Comment by shadowtime2000** [comment]
Actually we should probably use `:compile` instead of `:precompile` for the directive.

**Comment by aidenybai** [comment]
Would this be scoped changes, where only affected innerHTML elements are change? Seems sort of inefficient to compile and change the full innerHTML every mutation

**Comment by shadowtime2000** [comment]
Yeah, we should probably use some sort of technique to allow vdom diffing. Maybe supply a utility function like `createElement` which can be used? That could tie in to #7 where I believe we were thinking of supplying component views as strings, we could use something like `createElement` instead. Maybe parse the string and convert it to use `createElement`.

**Comment by aidenybai** [comment]
Agreed. Currently VDom refactor is priority so we can implement these changes

**Comment by shadowtime2000** [comment]
Something that could get some discussion started:
```html
<div l-use="MoneyInBank">
	<div l-templating:compile="this.compile">
		Money: $<%= it.money %>
	</div>
	<div l-on:effect="this.money = getMoneyAmount()"></div>
</div>
```
```js
import { compile } from "eta";

Lucia.use("MoneyInBank", {
	compile,
	money: 0,
	getMoneyAmount: getMoneyAmountFromDatabaseHere
});
```

**Comment by shadowtime2000** [comment]
Could also look into instead allowing users to create plugins for template engines, `lucia-eta`, which use the template engine to parse the content and dynamically generate VDom nodes.

**Comment by aidenybai** [comment]
Yeah, could be interesting. Maybe we should also have plugin support in mind

**Comment by shadowtime2000** [comment]
I think the best approach would be to use its parsing engine and  parse it into a structure we can convert into a vdom tree

**Comment by shadowtime2000** [comment]
I think the best way is to use some DOM diffing algo which merges the rendered template with the current text.

**Comment by aidenybai** [comment]
With the benefit of hindsight a couple months later, it's probably smarter to just allow server-rendered templates and have the functionality be the same as it is now. @shadowtime2000 feel free to close the issue if you agree

**Comment by shadowtime2000** [comment]
@aidenybai I think we could just try a basic embedded template engine where `{{ soemthing }}` is equal to a text node while `{{{ something }}}` is equal to an element or something being made with `innerHTML` being set. Still not very sure about how `{{{ something }}}` would work. If your fine with it, I could draft up a PR

**Comment by aidenybai** [comment]
That sounds great! I tried to do some template compilation to our own `l-text`/`l-html` directives, but I wasn't successful

```html
<p>hello {{ name }}</p> ---> <p>hello <span l-text="name"></span></p> or <p l-text="'hello ' + name"></p>
```
