### ISSUE TITLE
Remove Side Effects

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#24]
**Is your feature request related to a problem? Please describe.**
Lucia has partial support for tree shaking but not full support because it has side effects with accessing the `document`.

**Describe the solution you'd like**
Removal of [src/index.ts L#47](https://github.com/aidenybai/lucia/blob/5a67ef80cf6cf22f78b55cdfdf9383527585d327/src/index.ts#L47).

**Additional context**
To my understanding the only side effects come from that initialization thing, so once that is done this would support full tree shaking. Again, this is a breaking change so we should probably put it in the `vdom-refactor` branch (#8).

**Comment by shadowtime2000** [comment]
@aidenybai What are your thoughts on this? Looking at the semver document we are allowed to have breaking changes if the major version is `0`. 
![image](https://user-images.githubusercontent.com/66655515/100159762-36258280-2e63-11eb-9e3c-cee8a27474c6.png)

**Comment by aidenybai** [comment]
Yeah, I think its fine. There currently is not much "production" usage and versions don't change. Personally, I don't think its a huge deal as long as we incrementally make breaking changes

**Comment by shadowtime2000** [comment]
@aidenybai Not fully understanding what you are saying, are you agreeing with removing side effects and publishing with `v0.3.0` or something?

**Comment by aidenybai** [comment]
Oh I see, I didn't understand the question completely. The main issue with the removal of the automatic initiation on dom load is that it partially contradicts the "ability to do logic in the markup." We should discuss this further.

For the vdom tree shaking, it also depends on utils and directives. If we want to fully support tree shaking, we should also consider restructing our fs

**Comment by shadowtime2000** [comment]
Yes, true. This should be discussed more.

**Comment by shadowtime2000** [comment]
We could remove the current side effect from `index.ts`. Then we could create a `browser.ts` which exports everything in `index.ts` but also has that DOM side effect. We could then modify the current rollup config to use `browser.ts` for UMD and IIFE exports while using `index.ts` for CJS and ES.

**Comment by aidenybai** [comment]
> We could remove the current side effect from `index.ts`. Then we could create a `browser.ts` which exports everything in `index.ts` but also has that DOM side effect. We could then modify the current rollup config to use `browser.ts` for UMD and IIFE exports while using `index.ts` for CJS and ES.

This seems like an interesting fix - does this mean CJS builds need manual initialization?

**Comment by shadowtime2000** [comment]
@aidenybai Yes, but I think it is safe to assume that if they are using a more controlled module system like CJS and ES they want full control over how it is initialized.

**Comment by aidenybai** [comment]
@shadowtime2000 Sounds good, you can push those changes. I will add a note on docs for CJS/ES

**Comment by shadowtime2000** [comment]
I finished that. I guess this will go along with the next release.
