### ISSUE TITLE
Quality Tests

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/lucia#25]
**Is your feature request related to a problem? Please describe.**
Current tests are quite subpar and don't really cover all cases. Current coverage is 67%

**Describe the solution you'd like**
Shift focus from features to writing quality tests.

**Comment by shadowtime2000** [comment]
I can work on this. 

> Shift focus from features to writing quality tests.

This would probably be best, cause it was hard to update the tests with all the features coming in. Good coverage is good for knowing what is tested, but if it over 90% it can make the project look better.

**Comment by aidenybai** [comment]
I agree. I've also found a slew of bugs just by testing randomly, and I think fully testing everything a couple times over can help squash bugs and find issues.

**Comment by shadowtime2000** [comment]
Yeah I did find a bug with what I believe was the intended use of the `l-html` directive.

**Comment by shadowtime2000** [comment]
Yeah, our current goal should be to fix bugs, write tests, and optimize performance. We should also be releasing them all along the way.

**Comment by aidenybai** [comment]
Should be over 90% now.
