### ISSUE TITLE
Size Limit

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#29]
**Is your feature request related to a problem? Please describe.**
We should probably add some CI like GH actions with `size-limit` to make sure we stay under a maximum UMD bundle size of 4 - 5 KB.

**Describe the solution you'd like**
GH action using `size-limit`.

**Additional context**
Big bonus is it tells us how the size increases or decreases on PRs.

**Comment by shadowtime2000** [comment]
@aidenybai Thoughts?

**Comment by aidenybai** [comment]
That sounds like a good idea. I will look into that

**Comment by shadowtime2000** [comment]
For reference [the `size-limit` repo is ai/size-limit](https://github.com/ai/size-limit). Another bonus is that it can make it easier to figure out if the build still runs properly when dependabot creates a PR to update Rollup or a Rollup dep.
