### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/lucia#3]
**Is your feature request related to a problem? Please describe.**
Testing can help with making sure new changes don't break the code base as well as asserting everything is in order.

**Describe the solution you'd like**
Use a testing library like `jest` or `tape` to write tests for the current codebase (like directives, vdom, etc)

**Describe alternatives you've considered**
Possibly using the native `assert` library, don't really know the diff between that and mainstream.

**Additional context**
N/A

**Comment by shadowtime2000** [comment]
I have experience with `jest` and `mocha` but I think `jest` might be more fit for this. I will take a go at this.

**Comment by aidenybai** [comment]
That would be awesome - thanks shadow

**Comment by shadowtime2000** [comment]
Maybe some unit tests to just test the basic workings of the everything and some integration tests to see how they work in the `jsdom`. I don't know much about how to classify tests so that is just what I am going to call them 😆

**Comment by aidenybai** [comment]
😆 Yeah that's probably fine, just some "tests" just to check nothing is broken I guess

**Comment by shadowtime2000** [comment]
This would be closed by #10. @aidenybai Do you think we should attach a CI such as Travis CI and a Coveralls to check test status and report coverage?

**Comment by aidenybai** [comment]
That would be smart - let me look into that

**Comment by aidenybai** [comment]
Travis should be setup 👍

**Comment by shadowtime2000** [comment]
@aidenybai Can you add some coverage reporting tool? I strongly recommend [coveralls](https://coveralls.io)
