### ISSUE TITLE
Remove IE Polyfills

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#31]
**Is your feature request related to a problem? Please describe.**
Currently when building, TS seems to be injecting polyfills and stuff for things like rest and spread operator. This seems pretty unnecessary because IE support should be optional for people who don't want to support it.

**Describe the solution you'd like**
Lucia not implementing IE polyfills and stuff to maintain a low bundle size.

**Comment by shadowtime2000** [comment]
I think compiling to `ES2020` might be a good option, and then maybe providing a larger build with the polyfills with Babel.

**Comment by shadowtime2000** [comment]
Or we could also just limit usage of ES6+ syntax, besides easily compiled ones such as `const`, `let` and arrow functions, though that seems a little unproductive.

**Comment by aidenybai** [comment]
Just pushed a change to support this - feel free to adjust. I think we can rollback the Object.assign as it no longer uses helpers in the slim builds

**Comment by shadowtime2000** [comment]
Strangely enough, if we use `ES2015+` for the TS build, it replaces the spread operators with `Object.assign`.

**Comment by shadowtime2000** [comment]
Looks good, but we should probably change it from `dist/polyfills` to `dist/legacy`.

**Comment by aidenybai** [comment]
Implemented in 8afd15377033b32051cc4ade4b1ddb3bad855a43
