### ISSUE TITLE
Drop `l-use` syntax in favor for Vue syntax

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/lucia#33]
**Is your feature request related to a problem? Please describe.**
Currently users can access their views by creating Lucia apps in JavaScript using `Lucia.use` and a target `l-use` directive.

**Describe the solution you'd like**
Scrap the `Lucia.use`, change `l-init` to `l-use`, and provide examples using the internal "Vue" syntax only

**Comment by shadowtime2000** [comment]
Hmm, I am not that familiar with Vue and it's syntax. @aidenybai Can you give an example of what it would look like with Lucia?

**Comment by aidenybai** [comment]
Current syntax:
```js
Lucia.use('name', { view }, ...components);
```
Vue-ish Syntax
```js
const app = Lucia.createApp({ view });
app.component('name', () => {});
app.component('name', () => {});

```

**Comment by shadowtime2000** [comment]
I think that seems like a good idea.

**Comment by aidenybai** [comment]
Done in 14d4c14ff6175ff430275292be943d023c5387b6
