### ISSUE TITLE
support sfc?

### ISSUE THREAD

**Issue by buttercubz** [aidenybai/lucia#40]
any plan to add support for single file components? maybe base on html component

**Comment by shadowtime2000** [comment]
I believe we talked about this a little in #7, we would have to discuss how they would be structured though.

**Comment by aidenybai** [comment]
I think @shadowtime2000 has already made some progress on this with `luciascript`

**Comment by shadowtime2000** [comment]
`luciascript` was meant to be the base of `lucia-jsx`, I don't know much about SFCs because I work mainly with React. We could probably borrow and properly credit the code from various compilers like `vue-loader`, Svelte, or [Prism web component compiler](https://github.com/kaleidawave/prism).

**Comment by aidenybai** [comment]
Will reopen when it is necessary to create SFC for Lucia
