### ISSUE TITLE
[FEATURE] ESM and CJS build

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#5]
**Is your feature request related to a problem? Please describe.**
Inserting `script` tags into the `head` tag isn't very organized especially for somewhat complex projects.

**Describe the solution you'd like**
An ESM build along with a CJS build.

**Describe alternatives you've considered**
None.

**Additional context**
I can do this in a PR just checking what people are thinking about this.

**Comment by aidenybai** [comment]
Just pushed builds for cjs, esm, and iife, may need some testing to make sure it's compatible to use with bundlers
