### ISSUE TITLE
Usage of web workers to accelerate critical processes

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/lucia#60]
**Is your feature request related to a problem? Please describe.**
Currently performance is done on a single thread (main thread), and this may cause operation blocking and decrease performance.

**Describe the solution you'd like**
Create code that moves critical processes to a separate web worker, so that operations can be offloaded and multithreaded. Some critical processes include `compile`, `render`, and the directives.

**Describe alternatives you've considered**
We could also consider debouncing directives, kind of like a simplified concurrent mode for React.

**Additional context**
Inspiration: https://github.com/niutech/vue-in-web-worker

**Comment by shadowtime2000** [comment]
There wouldn't be much benefit of offloading `compile`, but we could look into splitting different stuff which uses different components into their own threads and post messages for state updates, not quite sure how well it would work with `l-for`. We would also have to force the state to be JSON so we could send it as a payload to the workers as a string.

**Comment by shadowtime2000** [comment]
Like if we had:
```html
<div l-text="asdf"></div>
```
The responsibility of updating its text would be in it's own worker.

**Comment by aidenybai** [comment]
@shadowtime2000 That's a good point - we should try it out. I wonder if its too heavy on memory
