### ISSUE TITLE
Add Components

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/lucia#7]
**Is your feature request related to a problem? Please describe.**
I want to create multiple groups of elements that can be reused.

**Describe the solution you'd like**
Ability to use components (ex: <my-component></my-component>)

**Describe alternatives you've considered**
Not having components, or just grouping them somehow

**Comment by shadowtime2000** [comment]
What do you think the syntax should look like? Maybe have it use the Web Components API or our own version of that (insert stuff into custom element tags in the VDOM).

**Comment by aidenybai** [comment]
We should use own version - Web Components API is pretty complicated and doesn't have a lot of compatibility with other browsers. 

We may need to try to restructure the internal architecture into an actual Virtual DOM for this to work though - Right now it really only acts like a reference.

Could also look into `<template>` tags

**Comment by shadowtime2000** [comment]
I like the name. If we are going the route of giving a cool name to our VDOM engine and have it operate in it's own folder to be imported, we could also think about publishing it in it's own package and make it a little bit more modular to work with other frameworks. @aidenybai @octetd Thoughts?

**Comment by shadowtime2000** [comment]
We could try allowing usage of SFCs too. Maybe something like what Vue does?
```vue
<template>
	<p l-text="this.count"></p>
	<button l-on:click="this.count++">Increment!</button>
</template>

<script>
{
	count: 0
}
</script>

<style>
button {
	width: 100%;
}
</style>
```
Which would basically become the same as
```js
import { Component } from "lucia";
import "./counter.css";

const comp = new Component();
comp.use({ count: 0 });
comp.view("<p l-text='this.count'></p><button l-on:click='this.count++'>Increment!</button>");

export default comp;
```

**Comment by aidenybai** [comment]
Could be interesting - I would much rather modularize and have a sfc package for this, just to reduce overhead

**Comment by shadowtime2000** [comment]
Yeah, the converted part could probably be part of the core package and the SFC could become a `lucia-sfc` package with a compiler and parser.

**Comment by shadowtime2000** [comment]
We could also probably do JSX then,

```jsx
import { l, useState } from "lucia-jsx";
import { Component } from "lucia";

function Counter() {
const [count, setCount] = useState(0);

return (<div><p l-text={count}></p><button l-on:click={() => setCount(count++);}>Increment!</button></div>);
}
```

or

```jsx
import { l, Component } from "lucia-jsx";

const Counter = Component((props, { count }) => (<div><p l-text={count}></p><button l-on:click={() => count++;}>Increment!</button></div>));
```

We would probably need to do some more planning on how exactly that would work though (More react like, or a new way?)

**Comment by aidenybai** [comment]
Agreed, the jsx syntax looks pretty good, we can explore other ways of doing it as well

**Comment by shadowtime2000** [comment]
Maybe for the core part:
```typescript
import { Component } from "lucia";

const Counter = Component({ name: "counter", state: { count: 0 }, view: "<p l-text='this.count'></p><button l-on:click='this.count++'>Increment!</button>" });
// or with chaining:
const Counter = Component({})
			.name("counter")
			.view("<p l-text='this.count'></p><button l-on:click='this.count++'>Increment!</button>")
			.use({ count: 0 });
const App = Luica.use("App", {}, [Counter]);

/* in HTML:
	<div l-use="App">
		<counter />
	</div>
*/
```
There is probably a better way for registering components than putting them inside an array or something.

**Comment by shadowtime2000** [comment]
There are 3 different ways we can make making components easier:
1. Single file components
2. JSX
3. Tagged Template Literals

And people can still just use the core base of the component system

**Comment by shadowtime2000** [comment]
For JSX we could probably create a utility package (`luciascript`?).

```typescript
import { l } from "luciascript";

l("div", { className: "card" }, [
  l("div", { className: "card-title" }, "Foo!"),
  l("div", { className: "card-body" }, "Foo!")
]);

/* Returns
<div class="card">
	<div class="card-title>Foo!</div>
	<div class="card-body">Foo!</div>
</div>
*/
```

**Comment by aidenybai** [comment]
I wonder if we can have a namespace for lucia on npm, for example `@lucialand/jsx` or `@lucialand/script`

**Comment by shadowtime2000** [comment]
@aidenybai We could do that but that would require an NPM organization and I don't think that is completely necessary at this stage of the project.

**Comment by shadowtime2000** [comment]
For organization I am going to move this to the in discussion column in the backlog because we are still trying to figure out how to implement this and what the interface/API should be.

**Comment by aidenybai** [comment]
Normal components implemented in 72fa4a93bf111dc78ec5994e6dbfff1ea9ed1b28. SFCs pending

**Comment by shadowtime2000** [comment]
@aidenybai Using that commit, how exactly would one simply make a counter component equivalent to the clicker game we gave?

**Comment by aidenybai** [comment]
@shadowtime2000 

That would just be 

```html
<div l-use="ClickerApp">
  <Clicker></Clicker>
</div>
```

```js
const Clicker = Lucia.component(
  'Clicker',
  '<button l-text="this.count" l-on:click="++this.count">0</button>'
); // Returns an object

Lucia.use(
  'App',
  { count: 0 },
  Clicker
);
```

**Comment by shadowtime2000** [comment]
What do you think about allowing components to have their own isolated state?

**Comment by aidenybai** [comment]
Will look into that and follow up if I have something

**Comment by shadowtime2000** [comment]
> @shadowtime2000
> 
> That would just be
> 
> ```
> <div l-use="ClickerApp">
>   <Clicker></Clicker>
> </div>
> ```
> 
> ```js
> const Clicker = Lucia.component(
>   'Clicker',
>   '<button l-text="this.count" l-on:click="++this.count">0</button>'
> ); // Returns an object
> 
> Lucia.use(
>   'App',
>   { count: 0 },
>   Clicker
> );
> ```

@aidenybai It doesn't appear to be working. [CodePen](https://codepen.io/shadowtime2000/pen/wvzwZRY?editors=1111).

**Comment by shadowtime2000** [comment]
Nevermind, in the `Lucia.use` statement it was supposed to be `ClickerApp` not `App`.

**Comment by shadowtime2000** [comment]
@aidenybai Just a question, when rendering, is it using VDom diffing or something or is it just placing it straight on there?

**Comment by aidenybai** [comment]
It's currently just selectively placing it straight on there

**Comment by aidenybai** [comment]
Also as a follow up, can't figure out a good way to make isolated views, stashed changes for now.

**Comment by aidenybai** [comment]
Just thinking of isolated components from a design perspective also doesn’t really fit into how Lucia is currently. We encourage usage of component scopes, therefore I think components should try on their own component scope.

**Comment by shadowtime2000** [comment]
I think I will start trying to attempt to create a JSX package for Lucia. That would require a function which is Hastscript compatible which creates strings for the HTML. Because of how useful that could be, I am going to create it in a seperate package called `luciascript`.

**Comment by aidenybai** [comment]
Sounds great.

**Comment by shadowtime2000** [comment]
We should also probably allow functions for the template which take props passed to the usage of the component. Along with that we should probably have a special `children` prop which is a string of all the HTML in between the component tags.

**Comment by aidenybai** [comment]
I'm not sure if that makes sense to me - I imagine the component to be standalone and pluggable, basically with the functionality of `<Component />`

**Comment by shadowtime2000** [comment]
Components could still be standalone and pluggable, you would just be able to customize them more:
```html
<Button l-bind:theme="this.dark ? 'dark' : 'light'">Click here!</Button>

**Comment by shadowtime2000** [comment]
Maybe I don't have a full understanding of how the current Virtual DOM works, but couldn't we allow users to have the template of a component be the result of an `h` function? @aidenybai Thoughts?

**Comment by aidenybai** [comment]
We can, but the current render function just creates an object representation, so I made an intermediate function `render` to do that. Maybe we can have the internal compiler use h, and have the exported function be render, which returns the template as you mentioned

**Comment by shadowtime2000** [comment]
@aidenybai Do you think with the current architecture we could facilitate allowing functional components with props?
```html
<Button l-bind:dark="this.dark">Click Here</Button>
```
```js
Lucia.component("Button", ({ dark, children }) => `<button class='button button-${dark ? 'dark' : 'light'}'>${children}</button>`);
```

**Comment by aidenybai** [comment]
This is possible - is `this.dark` a prop in the component scope? So view props from scope parent need to be passed down? If so, maybe we should consider a better way of `l-bind`ing multiple props.

**Comment by shadowtime2000** [comment]
> So view props from scope parent need to be passed down?

Yeah, this is what I am imagining to allow being unopinionated with naming conventions.

> If so, maybe we should consider a better way of l-binding multiple props.

Yeah, we should come up with a better way of passing props down to components without `l-bind`.

**Comment by aidenybai** [comment]
@shadowtime2000 Could we just pass the entire view into the function and allow it to be destructured for whatever is needed?

**Comment by aidenybai** [comment]
Nevermind, that doesn't make any sense. Ignore what I just said
