### ISSUE TITLE
Restructure core to Virtual DOM

### ISSUE THREAD

**Issue by aidenybai** [aidenybai/lucia#8]
**Is your feature request related to a problem? Please describe.**
Currently Lucia runs off a "reference Virtual DOM" and makes DOM related changes based on that. This way, it supports #7 

**Describe the solution you'd like**
Currently the vdom is a tree like structure with each layer/vnode containing selectors as "pointers"
Kind of inefficient if we do not want to go with the traditional vdom path, could just simplify to an array vs. a tree like structure.
Could also just implement a vdom.

**Comment by octetd** [comment]
Is anyone looking into this one already? I want to give it a shot, but first would need to decide which route to go with.

**Comment by aidenybai** [comment]
Hey @octetd, thanks for your interest. Using a DOM array would be easier - but Virtual DOM should be implemented. I have already tried a bit but it's based off of selectors which negates the point of having a mirror representation of the DOM.

**Comment by aidenybai** [comment]
Just a follow up - I can add you as a contributor if you think it will be easier for you.

**Comment by octetd** [comment]
Thanks for being so fast to get back to me, if you are confortable with adding me as a contributor it would help yes, might also help to create a project so commits can reference tasks and we can track overral progress.

**Comment by aidenybai** [comment]
Just sent an [invite to you](https://github.com/aidenybai/lucia/invitations). I haven't used Github Projects before - let me see if I can get that set up 👍

**Comment by octetd** [comment]
Do you have any channel where contributors might communicate aside from this issues system?

**Comment by aidenybai** [comment]
Not yet, I've been considering using discord though.

**Comment by octetd** [comment]
I will create a board to track progress on this issue so I can break it into tasks, is that ok?

**Comment by shadowtime2000** [comment]
That seems like a good idea.

**Comment by aidenybai** [comment]
Yep, that's fine

**Comment by aidenybai** [comment]
Just created a discord server - feel free to join if you want: https://discord.gg/q2pSU39

**Comment by shadowtime2000** [comment]
We should also probably just have a `vdom` branch which we can all send PRs to and then eventually merge that into master. I am thinking PRs because we can review each others work. Refactors and chores could just be pushed I guess.

**Comment by aidenybai** [comment]
That sounds like a great idea. Just pushed a branch

**Comment by shadowtime2000** [comment]
I like the name. If we are going the route of giving a cool name to our VDOM engine and have it operate in it's own folder to be imported, we could also think about publishing it in it's own package and make it a little bit more modular to work with other frameworks. @aidenybai @octetd Thoughts?

**Comment by octetd** [comment]
I gave it a name and a folder to live in because I think it needs to be broken up into files for ease of maintenance @shadowtime2000 I'm making it quite modular and not too tightly coupled to lucia, I mean it's built for use by lucia but if someone wants to use it on their own project if they can work with the API it will likelly be very doable.
To me either having it as a repository and using it as a submodule, or outright publishing it as a package on npm can work@aidenybai thoughts?

**Comment by octetd** [comment]
@shadowtime2000 while I develop the first proper version of maestro I will likely push directly to the branch and not do PRs so the workflow can be a tad faster but afterwards I will go the PR route for sure.

**Comment by shadowtime2000** [comment]
Makes sense.

**Comment by aidenybai** [comment]
Both work - I want to make sure that everything flows and glues well before we publish. I can definetely see publishing maestro in the future though

**Comment by shadowtime2000** [comment]
One thing that is a little weird is that the `jest` coverage reporting doesn't seem to be working on the `vdom-refactor` branch.

**Comment by aidenybai** [comment]
Weird - is it because it's not being used in `index.ts`?

**Comment by shadowtime2000** [comment]
I made `vdom-refactor` up to date with commits in `master` and the coverage reporting seems to be working.

**Comment by shadowtime2000** [comment]
The `vdom-refactor` branch does have an extremely low test coverage of around 56% so we should probably work on that while developing it.

**Comment by aidenybai** [comment]
Sounds good. @octetd said on Discord that he was available to work on the project tomorrow and this weekend, I'm not super available tomorrow but I can work this weekend. Maybe we can push a semi-working prototype by the end of this weekend.

**Comment by octetd** [comment]
That's my expectation pretty much, to get something out even if using a very dumb conciliation alg by monday

**Comment by shadowtime2000** [comment]
Sounds good to me. I can also work on it tomorrow and over the weekend. I am going to start writing ways for it to easily integrate with Lucia like setting textContent and innerHTML.

**Comment by octetd** [comment]
Ok, just make sure any updates to a node mark it as `tainted`, I'm considering dropping `clean` as it's redundant, @shadowtime2000 @aidenybai thoughts?

**Comment by shadowtime2000** [comment]
@octetd I think removing `clean` would be a good idea.

**Comment by shadowtime2000** [comment]
How should we listen to data events? Should we do that within the VDom or should we have Lucia listen for data changes and render? I think having Lucia listen for changes would keep it more decoupled and more modular. @octetd @aidenybai Thoughts?

**Comment by octetd** [comment]
yeah I think it also better separates concerns, maestro has one job it's to manage the DOM on command so lucia should be in control here imo

**Comment by octetd** [comment]
I'm thinking about events, having it as props and allow binding of any function? or have a custom handler and have synthetic events

**Comment by aidenybai** [comment]
Would having a custom handler with synthetic events be unnecessary overload?

**Comment by shadowtime2000** [comment]
I think we should just go with props with function binding.

**Comment by aidenybai** [comment]
Yeah - one issue I face with that was not being able to manage event listeners very well, the current non-refactored solution uses the .onevent properties to attach events. Any ideas on this?

**Comment by shadowtime2000** [comment]
What about using `addEventListener`?

**Comment by aidenybai** [comment]
Yeah, that's what I was referring to with the weird api - There's not really a way to grab existing events, so it actually may be necessary to have an in memory mirror representation of events.

**Comment by shadowtime2000** [comment]
We could get a list of events with `Object.keys` and `filter` and then access the value for each event in the object.

**Comment by aidenybai** [comment]
Oh okay - I see 👍

**Comment by shadowtime2000** [comment]
Currently there are some `setWhateverValue` functions but users can still directly set the value. @octetd @aidenybai do you know any workarounds so we can still set `tainted` to `true` on value changes? I know about getters and setters but then it may become a little more messy.

**Comment by aidenybai** [comment]
Yeah I agree, the setter/getters looks pretty clunky. The only thing I can think of is maybe having a `Proxy` on `this` and tainting the `VDomNode` in a trap.

**Comment by shadowtime2000** [comment]
I have never used a `Proxy` with `this` so I am a little doubtful of how well that would go. I think we should just give warnings in the Maestro documentation for setting values like `textContent`.

**Comment by octetd** [comment]
Although messy I think setters would give the most consistent and missuse resistant API by ensuring tainting of the node

**Comment by shadowtime2000** [comment]
I changed the system to use getters and setters to ensure `tainted = true` and I dropped the `clean` property.

**Comment by aidenybai** [comment]
Looks good. I'll be able to work on this after 4pm pst - What do you guys think about renaming VDomNode to VNode

**Comment by shadowtime2000** [comment]
> What do you guys think about renaming VDomNode to VNode

Probably a good idea.

**Comment by shadowtime2000** [comment]
There seems to be a bug with the `nodeValue` in `fromHtmlElement` where it always becomes `undefined` even when it has content.

**Comment by shadowtime2000** [comment]
The coverage on the `vdom-refactor` branch has hit 87% higher than the coverage of the master branch which has a coverage of 81%. Some parts of it I found hard to test so I didn't test.

**Comment by aidenybai** [comment]
Looks good. Just from a developer experience standpoint, would it be better to turn the VDomNode constructor parameters to only accept an object, this way it allows for more clarity?

**Comment by octetd** [comment]
Hey @shadowtime2000 you pushed the refactors faster than me lol, can you roughly list what test you are finding hard please? @aidenybai I am looking into doing this rn.

**Comment by shadowtime2000** [comment]
@octetd Mainly the attributes to props conversion and children rendering in the `render` function.

**Comment by octetd** [comment]
ok, I have refactored the code to take an object in the constructor should be less messy to initialise the class now updating the tests and will push when done

**Comment by octetd** [comment]
I'm also dropping needsRender because it had the exact same body as isTainted

**Comment by octetd** [comment]
or should I leave needsRender and drop isTainted, opnions?

**Comment by aidenybai** [comment]
I would say leave needsRender as it is more descriptive, but keep the tainted property

**Comment by octetd** [comment]
I pushed the change to use an object as parameter to the constructor, it's way better nowwithout the long chains of undefined in the tests, good thing we did it now

**Comment by aidenybai** [comment]
I have a question about the uniqueKey - is it necessary in our use case? If the VDom is a tree, then we can determine VNode of the element by walking the tree and determining its relative position assuming it is ordered.

**Comment by octetd** [comment]
it's about say in a list keeping the order of the rendered elements and also diffing in the conciliation

**Comment by aidenybai** [comment]
Couldn't that also be achieved by getting the index of the VNode?

**Comment by octetd** [comment]
not exactly, at least not without flattening the tree esp for the diffing I have in mind I will try it if it dosn't work we can get rid of the key and also I have the idea of being able to access the nodes like a hashmap for that I need the key.

**Comment by aidenybai** [comment]
Got it :+1:

**Comment by octetd** [comment]
Ok, thanks

**Comment by shadowtime2000** [comment]
What is the status on this? I can see there are two files, a rewrite file for a VNode and the initial Vnode we created. I am a little confused on what the rewrite file is for.

**Comment by aidenybai** [comment]
Rewrite file is an experiment to create a functional API for vnodes. In master, basically rolling out the bugs to make sure that it is stable and no issues.

**Comment by shadowtime2000** [comment]
What do we need for Maestro to be completed? Diffing, reconciliation, I am don't know much about how exactly those would be implemented though.

**Comment by aidenybai** [comment]
Yeah, I'm currently working on some implementations but I haven't pushed. I can update if I get something good

**Comment by shadowtime2000** [comment]
This is kind of off topic but we can change the version in `vdom-refactor` to `v1.0.0` and release it with a `next` dist tag so users know it is still in development or is not entirely stable yet. This would allow people to try out the features like controlling initialization and the performance and compatibility benefits of not using `with`.

**Comment by shadowtime2000** [comment]
Continuing a conversation of #24, @aidenybai What do you think about merging `master` with `vdom-refactor` and publish as `v0.3.0` for the optimizations of not using `with` statements?

**Comment by shadowtime2000** [comment]
We could also just do it inside of `master` and publish it without touching `vdom-refactor`.

**Comment by aidenybai** [comment]
vdom-refactor is more long term. I agree we should just do it inside master

**Comment by aidenybai** [comment]
> Continuing a conversation of #24, @aidenybai What do you think about merging `master` with `vdom-refactor` and publish as `v0.3.0` for the optimizations of not using `with` statements?

Pushed breaking change in 7f6a6288304ba464b407d01164c2b83253b17666. Once we finish tests, I think its ready to push `0.3.0`

**Comment by shadowtime2000** [comment]
@aidenybai Seems good. What do you think we should target with test coverage? I am thinking 90%.

**Comment by aidenybai** [comment]
> @aidenybai Seems good. What do you think we should target with test coverage? I am thinking 90%.

90% seems like a good goal, but we can adjust if we pretty much covered all of the relevant parts

**Comment by aidenybai** [comment]
No progress on Maestro, closing until needed
