### ISSUE TITLE
Better State Management

### ISSUE THREAD

**Issue by shadowtime2000** [aidenybai/lucia#9]
**Is your feature request related to a problem? Please describe.**
It is kind of hard to manage state management links between Javascript and `l-use` scope components.

**Describe the solution you'd like**
An `l-watch` directive that points to a global that is checked on every render step to see if it changed, and if so, it would render the entire component.

**Describe alternatives you've considered**
A render function that is attached to DOM elements that are components.

**Comment by aidenybai** [comment]
I just want to quickly clarify to make sure I'm understanding:

So currently the `l-use` attribute handles an object either through directly providing it in the attr value or calling a existing function that returns an object. 

If that object is changed, then the component will update with the new code. If the object code is changed, how would we maintain the existing state of the properties? Say `count` prop is at 1, and we add a new `count2` prop - wouldn't that reset the original `count`?

A possible alternative solution could be passing object components through a proxy somehow, then trapping update calls

**Comment by shadowtime2000** [comment]
I think a proxy would work or just allowing users to control when to render.

**Comment by shadowtime2000** [comment]
I just want people to be able to do something like this:
```javascript
const comp = document.getElementById("app");
store.data.subscribe((newState) => comp.render(newState)); // Replace with state library specific code
```

**Comment by aidenybai** [comment]
So expose some API functionality to allow the developer to enter a custom callback?

**Comment by shadowtime2000** [comment]
Yes.

**Comment by shadowtime2000** [comment]
More of just a way to link a shared state between the Javascript and the Lucia components.

**Comment by aidenybai** [comment]
Understood. I'll push some functionality and let me know if you like it

**Comment by aidenybai** [comment]
Okay so I did a bit of experimenting - it's kind of awkward with the current way Lucia uses - Lucia exposes a createApp function on the global Lucia variable - where it's possible to hook a method on there providing this type of functionality and where `$patch` is exposed - however if using the `l-use` directive doesn't really support this type of thing, at least not something I can think of. Feel free to try this out

**Comment by shadowtime2000** [comment]
Looks like if you do something like this

```html
<div l-use="App">
  <button l-text="count" l-on:click="count++"></button>
</div>
```

```javascript
window.App = {
  count: 0
};
```
I think it may be Javascript object mutation but certainly without using a function you can have the `window.App` track changes that are performed in the component but when you change the state on `window.App.count` it doesn't change the UI until you do an action in which case it takes the previous state and adds on to that without ever showing the previous state.

**Comment by aidenybai** [comment]
Yeah, maybe we can have a `reactive` function where it can make objects reactive

**Comment by aidenybai** [comment]
Just implemented a `l-watch` directive and exposed components through `Lucia.components` property

**Comment by shadowtime2000** [comment]
@aidenybai I didn't have the time to play around with it but I believe `l-watch` is more of the Lucia version of React `useEffect` instead of more of the React `useEffect` dependency list. The current functionality is kind of nice so we could rename it to `l-effect` for side effects on render. I am looking into allowing Lucia to subscribe to value changes.

**Comment by shadowtime2000** [comment]
Looking into watching for changes there is a pretty popular library [on-change](https://github.com/sindresorhus/on-change) which could probably be easy to implement but it is roughly 27kb which could make the library around 30kb, though I think `rollup` with `terser` could decrease that size by a bit more. @aidenybai Thoughts?

**Comment by aidenybai** [comment]
Just took a look at the library, love the functionality. the 27kb raw size makes me a bit uncomfortable though - maybe we should try implementing our own solution in-house with similar functionality first. I think `observer.ts` already provides a proxy that traps changes, we could change this to a class with subscribe/etc. functions for state management. 

I think other libraries like vue have external state management libraries like vuex, maybe it's smarter to modularize

**Comment by shadowtime2000** [comment]
> I think other libraries like vue have external state management libraries like vuex, maybe it's smarter to modularize

I like this idea but then we would need to figure out how to organize different packages. Should we keep them all in one repo and use [bolt](https://github.com/boltjs/bolt) or [pnpm](https://pnpm.js.org) or we could create a Github organization with a name like `luciajs` and keep them in separate repos there.

**Comment by aidenybai** [comment]
I'm not sure yet - I think the best course of action could be to try to implement state management and see how it affects the code size or if it is possible with the current architecture. I guess we'll just have to see how it goes and do it from there

**Comment by aidenybai** [comment]
> Just implemented a `l-watch` directive and exposed components through `Lucia.components` property (kinda not intuitive right now)
> 
> Kind of implemented the functionality - double check if you want to change it.

Moved `l-watch` under `l-on:effect`, now able to access apps through `l-link`

**Comment by shadowtime2000** [comment]
You can view them, but you can't edit them. Changing it seems to just stop the entire app.

[CodePen example](https://codepen.io/shadowtime2000/pen/MWeopma?editors=1111)

**Comment by aidenybai** [comment]
Just found the issue - the object is being exported under the global `Lucia` namespace, but is static. Its being modified under the document load anon function, but it doesn't change the object in the global namespace - kinda.

Devtools seems to be saying that something is in there, but when you `console.log` it, it returns nothing. Weird issue

**Comment by aidenybai** [comment]
Should be fixed - feel free to write an optimization if you want

**Comment by shadowtime2000** [comment]
Seems to be working now. Whenever you change a value under `$view` it seems to do another render which is great. I think we should instead use a wrapper around the data given in `l-use` so that we can just track changes so people can keep it a little centralized.

**Comment by aidenybai** [comment]
Agreed, I'm also not sure of the implementation strategy. If we use a wrapper function, like `Lucia.use('example', {})`, which triggers a render and the target might be `l-use="example"`, how would we distinguish between anonymous objects like `l-use="{}"`? This also introduces additional a tiny bit of additional complexity and performance overhead (at least with the implementation I'm thinking of). I will try to push out some implementation for this.

Another solution could be directly replacing function references, which is kind of hard to do as you can't really identify the function names as well as this solution is pretty destructive.

**Comment by shadowtime2000** [comment]
Seems like the `Lucia.use` route is working. I am going to close this then.
